/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForCreatorsRouteImport } from './routes/for-creators'
import { Route as ForBrandsRouteImport } from './routes/for-brands'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiJobsRefreshTokensRouteImport } from './routes/api/jobs/refresh-tokens'
import { Route as ApiJobsPollOrdersRouteImport } from './routes/api/jobs/poll-orders'
import { Route as AuthenticatedAppSetupRouteImport } from './routes/_authenticated/app.setup'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app.products'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app.orders'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as ApiPublicTiktokWebhookRouteImport } from './routes/api/public/tiktok.webhook'
import { Route as AuthenticatedAppSettingsAccountRouteImport } from './routes/_authenticated/app.settings.account'
import { Route as AuthenticatedAppOrdersIdRouteImport } from './routes/_authenticated/app.orders.$id'
import { Route as ApiPublicTiktokOauthCallbackRouteImport } from './routes/api/public/tiktok.oauth.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCreatorsRoute = ForCreatorsRouteImport.update({
  id: '/for-creators',
  path: '/for-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBrandsRoute = ForBrandsRouteImport.update({
  id: '/for-brands',
  path: '/for-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiJobsRefreshTokensRoute = ApiJobsRefreshTokensRouteImport.update({
  id: '/api/jobs/refresh-tokens',
  path: '/api/jobs/refresh-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsPollOrdersRoute = ApiJobsPollOrdersRouteImport.update({
  id: '/api/jobs/poll-orders',
  path: '/api/jobs/poll-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSetupRoute = AuthenticatedAppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicTiktokWebhookRoute = ApiPublicTiktokWebhookRouteImport.update({
  id: '/api/public/tiktok/webhook',
  path: '/api/public/tiktok/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSettingsAccountRoute =
  AuthenticatedAppSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppOrdersIdRoute =
  AuthenticatedAppOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppOrdersRoute,
  } as any)
const ApiPublicTiktokOauthCallbackRoute =
  ApiPublicTiktokOauthCallbackRouteImport.update({
    id: '/api/public/tiktok/oauth/callback',
    path: '/api/public/tiktok/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-creators': typeof ForCreatorsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/orders': typeof AuthenticatedAppOrdersRouteWithChildren
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/setup': typeof AuthenticatedAppSetupRoute
  '/api/jobs/poll-orders': typeof ApiJobsPollOrdersRoute
  '/api/jobs/refresh-tokens': typeof ApiJobsRefreshTokensRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/orders/$id': typeof AuthenticatedAppOrdersIdRoute
  '/app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/api/public/tiktok/webhook': typeof ApiPublicTiktokWebhookRoute
  '/api/public/tiktok/oauth/callback': typeof ApiPublicTiktokOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-creators': typeof ForCreatorsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/orders': typeof AuthenticatedAppOrdersRouteWithChildren
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/setup': typeof AuthenticatedAppSetupRoute
  '/api/jobs/poll-orders': typeof ApiJobsPollOrdersRoute
  '/api/jobs/refresh-tokens': typeof ApiJobsRefreshTokensRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/orders/$id': typeof AuthenticatedAppOrdersIdRoute
  '/app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/api/public/tiktok/webhook': typeof ApiPublicTiktokWebhookRoute
  '/api/public/tiktok/oauth/callback': typeof ApiPublicTiktokOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-creators': typeof ForCreatorsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRouteWithChildren
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/app/setup': typeof AuthenticatedAppSetupRoute
  '/api/jobs/poll-orders': typeof ApiJobsPollOrdersRoute
  '/api/jobs/refresh-tokens': typeof ApiJobsRefreshTokensRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/orders/$id': typeof AuthenticatedAppOrdersIdRoute
  '/_authenticated/app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/api/public/tiktok/webhook': typeof ApiPublicTiktokWebhookRoute
  '/api/public/tiktok/oauth/callback': typeof ApiPublicTiktokOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/for-brands'
    | '/for-creators'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app'
    | '/app/onboarding'
    | '/app/orders'
    | '/app/products'
    | '/app/settings'
    | '/app/setup'
    | '/api/jobs/poll-orders'
    | '/api/jobs/refresh-tokens'
    | '/app/'
    | '/app/orders/$id'
    | '/app/settings/account'
    | '/api/public/tiktok/webhook'
    | '/api/public/tiktok/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/for-brands'
    | '/for-creators'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/onboarding'
    | '/app/orders'
    | '/app/products'
    | '/app/settings'
    | '/app/setup'
    | '/api/jobs/poll-orders'
    | '/api/jobs/refresh-tokens'
    | '/app'
    | '/app/orders/$id'
    | '/app/settings/account'
    | '/api/public/tiktok/webhook'
    | '/api/public/tiktok/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/for-brands'
    | '/for-creators'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/_authenticated/app'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/products'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/setup'
    | '/api/jobs/poll-orders'
    | '/api/jobs/refresh-tokens'
    | '/_authenticated/app/'
    | '/_authenticated/app/orders/$id'
    | '/_authenticated/app/settings/account'
    | '/api/public/tiktok/webhook'
    | '/api/public/tiktok/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForBrandsRoute: typeof ForBrandsRoute
  ForCreatorsRoute: typeof ForCreatorsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  ApiJobsPollOrdersRoute: typeof ApiJobsPollOrdersRoute
  ApiJobsRefreshTokensRoute: typeof ApiJobsRefreshTokensRoute
  ApiPublicTiktokWebhookRoute: typeof ApiPublicTiktokWebhookRoute
  ApiPublicTiktokOauthCallbackRoute: typeof ApiPublicTiktokOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-creators': {
      id: '/for-creators'
      path: '/for-creators'
      fullPath: '/for-creators'
      preLoaderRoute: typeof ForCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-brands': {
      id: '/for-brands'
      path: '/for-brands'
      fullPath: '/for-brands'
      preLoaderRoute: typeof ForBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/jobs/refresh-tokens': {
      id: '/api/jobs/refresh-tokens'
      path: '/api/jobs/refresh-tokens'
      fullPath: '/api/jobs/refresh-tokens'
      preLoaderRoute: typeof ApiJobsRefreshTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/poll-orders': {
      id: '/api/jobs/poll-orders'
      path: '/api/jobs/poll-orders'
      fullPath: '/api/jobs/poll-orders'
      preLoaderRoute: typeof ApiJobsPollOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/setup': {
      id: '/_authenticated/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AuthenticatedAppSetupRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/tiktok/webhook': {
      id: '/api/public/tiktok/webhook'
      path: '/api/public/tiktok/webhook'
      fullPath: '/api/public/tiktok/webhook'
      preLoaderRoute: typeof ApiPublicTiktokWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/settings/account': {
      id: '/_authenticated/app/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AuthenticatedAppSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/orders/$id': {
      id: '/_authenticated/app/orders/$id'
      path: '/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AuthenticatedAppOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAppOrdersRoute
    }
    '/api/public/tiktok/oauth/callback': {
      id: '/api/public/tiktok/oauth/callback'
      path: '/api/public/tiktok/oauth/callback'
      fullPath: '/api/public/tiktok/oauth/callback'
      preLoaderRoute: typeof ApiPublicTiktokOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppOrdersRouteChildren {
  AuthenticatedAppOrdersIdRoute: typeof AuthenticatedAppOrdersIdRoute
}

const AuthenticatedAppOrdersRouteChildren: AuthenticatedAppOrdersRouteChildren =
  {
    AuthenticatedAppOrdersIdRoute: AuthenticatedAppOrdersIdRoute,
  }

const AuthenticatedAppOrdersRouteWithChildren =
  AuthenticatedAppOrdersRoute._addFileChildren(
    AuthenticatedAppOrdersRouteChildren,
  )

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsAccountRoute: typeof AuthenticatedAppSettingsAccountRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsAccountRoute: AuthenticatedAppSettingsAccountRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRouteWithChildren
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppSetupRoute: typeof AuthenticatedAppSetupRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRouteWithChildren,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppSetupRoute: AuthenticatedAppSetupRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForBrandsRoute: ForBrandsRoute,
  ForCreatorsRoute: ForCreatorsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  ApiJobsPollOrdersRoute: ApiJobsPollOrdersRoute,
  ApiJobsRefreshTokensRoute: ApiJobsRefreshTokensRoute,
  ApiPublicTiktokWebhookRoute: ApiPublicTiktokWebhookRoute,
  ApiPublicTiktokOauthCallbackRoute: ApiPublicTiktokOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
