// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgsyadxeutselxseqfej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnc3lhZHhldXRzZWx4c2VxZmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNjIwODQsImV4cCI6MjA5NDkzODA4NH0.U17-A4IckeEZ4Bccd1HrX9mRQD8L5qmE8hKoPTlnPpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});